query pageQuery {
  ...LayoutQueryFragment
  projectConnection {
    edges {
      node {
        id
        date
        title
        description
        _sys {
          filename
        }
      }
    }
  }
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query blogPostQuery($relativePath: String!) {
  ...LayoutQueryFragment
  project(relativePath: $relativePath) {
    ...ProjectParts
  }
}
